name: Build and deploy

on:
  push:
    branches: [ main, master ]
    tags:
      - "v*"
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

      # from https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      #   we can extrac the branch name this way.  for a PR, we want ${{ github.head_ref }}
      #   but, for plain master, we will need this.  this can be accessed with:
      #   ${{ steps.extract_branch.outputs.branch }}
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

      # from https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
      # get the tag name if it exists
    - name: Extract tag name
      id: extract_tag_name
      shell: bash
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Use Node
      uses: actions/setup-node@v1

    - run: npm install
    - run: npm run build

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./_dist s3://digger-training-modules-app/${{ steps.extract_tag_name.outputs.tag || github.head_ref || steps.extract_branch.outputs.branch }} --delete
