name: Build and deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

      # from https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      # get the branch name from the repo
      # usable like: ${{ steps.extract_branch.outputs.branch }}
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Use Node
      uses: actions/setup-node@v1

    - run: npm run build

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./ s3://digger-training-modules-app/${{ steps.extract_branch.outputs.branch }} --delete
